Friendship Milestone
haraphat01/ror-social-scaffold pull request #2
Opened 2020-08-26 15:39 UTC by haraphat01

I just finished with the friendship milestone as requested in the project. I added the friendship model to the database and included the necessary associations between the User and Friendship. 

I am having an issue with rspec, I spent hours trying to fix it but all proved abortive, I'd fix it all the testing on the next milestone.

Thank you

2020-08-26 17:02 UTC, maelfosso requested changes
# Changes required :red_circle: 

Hello,

Thank you for this introduction :+1: 
However, there are some missing requirements

1. Kindly fix the errors  from Github Actions

2. As indicated [here], Posts timeline includes only posts written by logged-in user and their friends. It's not the case in your web app.

3. I am connected as **Bob Bar**. In the user's list, there should be a link for friendship request, as indicated [here], 
![Screenshot at 2020-08-26 17:57:00](https://user-images.githubusercontent.com/8848104/91333554-a3266f00-e7c5-11ea-8cb3-b6dc8a1c70c1.png)
From that screenshot, you can notice that is not the case. Don't forget to add also into the Single user page

****Friendship** is the main requirements of this milestone**

4. Implement the **unit tests** (for all the models)  and **integration tests** (for all the main features) as requested [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/tests.png)

Kindly make the changes and submit a new code review request
Thanks

Mael FOSSO

2020-08-27 09:31 UTC, haraphat01 commented
Thank you for the first review, I have made the necessary changes as pointed by the TSE.  Kindly check for your kind approval.

2020-08-27 10:21 UTC, uryelah requested changes
Hi **Arafat Akata**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with the fixes, there's just an issue with the views having too much logic in it but you should be able to move forth after a quick refactoring.

# Required Changes 🏗️ 🐛 💡

(Check comments below)

-----

 **Kindly fix the pointed out issues and comments below before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-08-27 10:21 UTC, uryelah commented on app/views/users/index.html.erb
> +                <td><%= link_to '<button type="button">Unfriend</button>'.html_safe, friendship_path(user), method: :delete, data: { confirm: "Are you sure you want to Unfriend"} %></td>
- [ ] Let's move this whole logic block foe the friendship buttons into a helper method. Remember to avoid view logic directly at views.

2020-08-27 10:21 UTC, uryelah commented on app/views/users/show.html.erb
> +  <% unless current_user == @user %>
- [ ] Same as above, you'll be also able to avoid code repetition and reuse the helper method her by refactoring view logic.

2020-08-27 20:02 UTC, haraphat01 commented
Thank you for the review, I have reworked on the issues and resubmitted.

2020-08-27 20:38 UTC, lekegitrepo requested changes
### Status: Request changes :recycle:
#### Hi @haraphat01 :clap: :clap:
#### Good job so far :muscle:  you are almost there.

**_Check my comment below for the required change._**

#### _Reviewed by Temitayo Adeleke._

2020-08-27 20:38 UTC, lekegitrepo commented on app/views/users/_request.html.erb
> +<% end %>
- **_Since the partial is part of the view it is better to move the logic to helper_**

2020-08-27 23:02 UTC, haraphat01 commented
Thank you for the review, I have reworked on the issues and resubmitted for approval.

2020-08-27 23:33 UTC, rOluochKe approved these changes
Hello Team!
### Well done, you got this right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the milestone, good luck with the next milestone.
- Happy coding!

2020-08-28 06:47 UTC, merged